apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{.Values.namespace}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name : http-{{ .Values.service.name }}
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}