name: Web Api (CI/CD)

#on:
#  push:
#    branches: [master, main]
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
    #paths:
    #  - 'scripts/deployment.yaml'
    #  - 'scripts/service.yaml'
    #  - 'charts/hello-world/**'
    #  - 'charts/hello-world/values.yaml'
    #  - 'charts/hello-world/templates/deployment.yaml'
    #  - 'charts/hello-world/templates/service.yaml'
    #  - '.github/workflows/maven.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Clear Helm version cache
      uses: actions/cache@v2
      with:
       path: /opt/hostedtoolcache/helm
       key: helm
       restore-keys: |
         helm-
    #- name: Set up Helm
    #  uses: azure/setup-helm@v1
    #  with:
    #    helm-version: '3.7.0'
    #- name: Check Helm version
    #  run: helm version    
    #- name: setting the azure kubernetes context
    #  uses: Azure/k8s-set-context@v1
    #  with:
    #    kubeconfig: ${{ secrets.KUBE_CONFIG_MSA2 }}
    #- name: Get Kubernetes nodes
    #  run: |
     #   kubectl get nodes
    #- name: Deploy Helm chart
     # run: |
        #helm upgrade --install my-release charts/hello-world
      #  helm upgrade my-release ./charts/hello-world  --install --wait --values=./charts/hello-world/values.yaml
    #- name: Deploy
    #  uses: WyriHaximus/github-action-helm3@v2
    #  with:
    #    exec: helm upgrade my-release ./charts/hello-world  --install --wait --atomic --values=./charts/hello-world/values.yaml
    #    kubeconfig: '${{ secrets.KUBE_CONFIG_MSA2 }}'
    - name: Delete Helm Release
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm uninstall my-release
        kubeconfig: ${{ secrets.KUBE_CONFIG_MSA2 }}    
    
