name: Web Api (CI/CD)

on:
  push:
    branches: [master, main]
    paths:
      - 'scripts/deployment.yaml'
      - 'scripts/service.yaml'
      - '.github/workflows/maven.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setting the azure kubernetes context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_MSA2 }}
    - name: Get Kubernetes nodes
      run: |
        kubectl get nodes  
        
    
    
