name: Web Api (CI/CD)

on:
  push:
    branches: [master, main]
    paths:
      - 'scripts/deployment.yaml'
      - 'scripts/service.yaml'
      - 'charts/hello-world/**'
      - 'charts/hello-world/values.yaml'
      - 'charts/hello-world/templates/deployment.yaml'
      - 'charts/hello-world/templates/service.yaml'
      - '.github/workflows/maven.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: '3.7.0'
    - name: setting the azure kubernetes context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_MSA2 }}
    - name: Get Kubernetes nodes
      run: |
        kubectl get nodes
    - name: Deploy Helm chart
      run: |
        #helm upgrade --install my-release charts/hello-world
        helm upgrade app-yib-meta-api-service ./charts/hello-world  --install --wait --values=./charts/hello-world/values.yaml    
    
    
